FROM php:8.1-apache

RUN apt-get update
RUN apt-get install -y git

COPY docker/php-apache/default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"
