version: '3.5'

services:
  php-apache:
    container_name: php-backend-test
    build:
      context: .
      dockerfile: docker/php-apache/dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend-test

networks:
  backend-test:
    name: backend-test
